### ISSUE TITLE
Release notes and Java–JavaScript version mapping

### ISSUE THREAD

**Issue by inad9300** [Atmosphere/atmosphere.js-node#14]
Hi there!

Simple question over here: are there any release notes with regards to this package?

I'm also a bit confused by the versioning used by this package. [atmosphere-runtime](https://mvnrepository.com/artifact/org.atmosphere/atmosphere-runtime) is currently in 2.6.1, with 3.0.0-alpha2 in the horizon. By contrast, [npm's atmosphere.js](https://www.npmjs.com/package/atmosphere.js) and [maven's org.atmosphere.client/javascript](https://mvnrepository.com/artifact/org.atmosphere.client/javascript) are in 3.0.5. Is it OK to use Java's 2.6.1 and JavaScript's 3.0.5 together? What's the reason for this misalignment?

Thanks!

**Comment by jfarcand** [comment]
@inad9300 Yes, you are right you can use those versions altogether. They don't follow the same release version but they are always compatible.
